### PR TITLE
#36 - added jefferson.app and jefferson.router static functions

### PR DESCRIPTION
**Pull request by natoverse**
@darthtrevino

### CODE REVIEW

**Comment by darthtrevino** [comment]
:shipit:

**Comment by natoverse** [comment]
what's your publish process?

`gulp release`
`cd ../express-jefferson`
`npm publish express-jefferson`

?

**Comment by natoverse** [comment]
Looks like you are using tags.

**Comment by darthtrevino** [comment]
Yeah, there's a gulp task that will increment semver and push a tag: `gulp bump:minor`

**Comment by darthtrevino** [comment]
I would revert your package.json bump and use the gulp task instead

**Comment by natoverse** [comment]
Oh right, I forgot you had set that up.

**Comment by darthtrevino** [comment]
After it's tagged and committed in github, I'll run 
```
gulp release
irish-pub (an NPM executable, verifies what files are actually pushed to npm)
npm publish
```

**Pull request merged**
