### PR TITLE
Adding a 'proxies' section to the Jefferson configuration

### PR DESCRIPTION
**Pull request by darthtrevino**
* Proxies are objects with an 'init' method. The init method accepts a delegate middleware and returns a middleware function. It is expected that the proxy invokes the delegate.

### CODE REVIEW

**Comment by natoverse** [comment]
Looks good. I love mocha - makes that sort of test so easy.

**Comment by darthtrevino** [comment]
Mocha is great! We're also using supertest to directly test the express app object's responses https://github.com/visionmedia/supertest

**Comment by natoverse** [comment]
You should put a Promise example in the readme. I think proxies are a good compromise on the seam - no forced dependency, but the power to convert your middleware as needed. Means you can mix and match middleware types too, so you can pull in other libs that may not be promisified.

**Comment by darthtrevino** [comment]
It may be worthwhile to capture some common proxies that we consider to be useful and store them in a 'proxies' folder. Then clients could use `require('express-jefferson/promise-proxy')`

**Comment by natoverse** [comment]
:+1: to boilerplate proxies

**Comment by darthtrevino** [comment]
I think this PR is about ready to roll. When travis gives me the greenlight I'll merge it.

**Pull request merged**
